import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "./providers/AuthProvider";

const geistSans = localFont({
  src: [{ path: "../public/fonts/Geist-Regular.woff2", weight: "400" }],
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: [{ path: "../public/fonts/GeistMono-Regular.woff2", weight: "400" }],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Quadrant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
